name: release

on:
  workflow_call # assumes triggered by semver tag

permissions:
  packages: write
  contents: write

env:
  APP_NAME: 'ytd'
  DENO_VERSION: 'v1.46'

jobs:
  build-and-upload-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          # - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: |
          deno task build
          xz ${{ env.APP_NAME }}
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.APP_NAME }}.xz
          asset_name: ${{ env.APP_NAME }}_${{ matrix.os }}.xz
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ contains(github.ref, '-') }} # check is github.ref_name is a prerelease
          #body: "This is my release text" # seems cannot auto generate

  # see also: https://jsr.io/docs/publishing-packages#publishing-from-github-actions
  publish:
    runs-on: ubuntu-latest
    needs: build-and-upload-release
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.    
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
